apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: mongodb-exporter
  namespace: monitoring
  labels:
    app: mongodb-exporter
spec:
  ports:
  - name: mongodb-exporter
    port: 9104
    targetPort: 9001
    protocol: TCP
  selector:
    app: mongodb-exporter