apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      serviceAccountName: mongodb-exporter
      containers:
      - name: mongodb-exporter
        image: hypoport/prometheus-mongodb-exporter
        ports:
        - containerPort: 9090
        env:
          - name: MONGODB_URL
            value: "mongodb://root:psw@mongos-svc.default:27017"               #修改成mongodb地址
          - name: HTTP_AUTH
            value: "root:oasis-rd@h3c"                                #修改用户名