apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: rabbitmq-exporter
  namespace: monitoring
  labels:
    app: rabbitmq-exporter
spec:
  ports:
  - name: rabbitmq-exporter
    port: 9099
    targetPort: 9090
    protocol: TCP
  selector:
    app: rabbitmq-exporter