apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: mysql-exporter
  namespace: monitoring
  labels:
    app: mysql-exporter
spec:
  ports:
  - name: mysql-exporter
    port: 9104
    protocol: TCP
  selector:
    app: mysql-exporter