apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  type: NodePort
  ports:
  - name: alertmanager
    port: 9093
    protocol: TCP
    nodePort: 9093
  selector:
    app: alertmanager