apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: redis-exporter
  namespace: monitoring
  labels:
    app: redis-exporter
spec:
  ports:
  - name: redis-exporter
    port: 9121
    protocol: TCP
  selector:
    app: redis-exporter