kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage
  namespace: monitoring
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi