apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      serviceAccountName: mysql-exporter
      containers:
      - name: mysql-exporter
        image: docker.io/jfusterm/mysqld-exporter
        ports:
        - containerPort: 9104
        command: ["mysqld_exporter"]
        args: ["-config.my-cnf="/tmp/mysql/mysql.cnf""]  #修改配置
        volumeMounts:
          - name: config-volume
          mountPath: /tmp/mysql
      volumes:
        - name: config-volume
          configMap:
            name: mysql-exporter